import http from 'node:http';
import {readFile,stat,mkdir} from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import QRCode from 'qrcode';
import {fileURLToPath} from 'node:url';
import {catalog,drySides,generate,groceryTotals,services,schedule,today,dateOK,addDays,people} from '../src/planner.js';

const root=path.dirname(path.dirname(fileURLToPath(import.meta.url))), publicDir=path.join(root,'dist','client');
const dataDir=path.resolve(process.env.DATA_DIR||path.join(root,'data')); await mkdir(dataDir,{recursive:true});
const db=new DatabaseSync(path.join(dataDir,'family-table.sqlite'));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS households(id TEXT PRIMARY KEY, code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, master_hash TEXT NOT NULL, cook_hash TEXT NOT NULL, settings TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY, household_id TEXT NOT NULL, role TEXT NOT NULL, expires_at TEXT NOT NULL, FOREIGN KEY(household_id) REFERENCES households(id));
CREATE TABLE IF NOT EXISTS plans(household_id TEXT NOT NULL,date TEXT NOT NULL,slot TEXT NOT NULL,recipe_id TEXT,dry_side TEXT,liquid TEXT,confirmed INTEGER NOT NULL DEFAULT 0,started_at TEXT,served_at TEXT,served_by TEXT,corrected INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(household_id,date,slot));
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,household_id TEXT NOT NULL,date TEXT NOT NULL,kind TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS stock(household_id TEXT NOT NULL,item TEXT NOT NULL,available INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,PRIMARY KEY(household_id,item));
CREATE TABLE IF NOT EXISTS service_records(household_id TEXT NOT NULL,date TEXT NOT NULL,service_id TEXT NOT NULL,kind TEXT NOT NULL,served_at TEXT NOT NULL,served_by TEXT NOT NULL,corrected INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(household_id,date,service_id));
CREATE INDEX IF NOT EXISTS idx_service_records_household_date ON service_records(household_id,date);`);

const sha=x=>crypto.createHash('sha256').update(String(x)).digest('hex');
const id=()=>crypto.randomUUID(); const iso=()=>new Date().toISOString();
const defaultSettings=()=>({language:'te',timezone:'Asia/Kolkata',people,elders:['Rajamannar','Padma'],portions:Object.fromEntries(people.map(p=>[p,1])),excludes:[],rules:{liquidForElders:true,drySideAtLunch:true,fruitTwice:true,noRepeatDays:14},graceMinutes:10});
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>1e6)throw Error('Request too large')}return s?JSON.parse(s):{}}
function session(req){const token=(req.headers.authorization||'').replace(/^Bearer /,'');if(!token)return null;const row=db.prepare(`SELECT s.household_id,s.role,h.name,h.code,h.settings FROM sessions s JOIN households h ON h.id=s.household_id WHERE token_hash=? AND expires_at>?`).get(sha(token),iso());return row?{...row,settings:JSON.parse(row.settings),token}:null}
function plansFor(hid,from=addDays(today(),-28),to=addDays(today(),35)){return db.prepare(`SELECT date,slot,recipe_id recipeId,dry_side drySide,liquid,confirmed,started_at startedAt,served_at servedAt,served_by servedBy,corrected FROM plans WHERE household_id=? AND date>=? AND date<=? ORDER BY date, CASE slot WHEN 'breakfast' THEN 1 WHEN 'lunch' THEN 2 WHEN 'snack' THEN 3 ELSE 4 END`).all(hid,from,to).map(r=>({...r,confirmed:!!r.confirmed,corrected:!!r.corrected}))}
function savePlans(hid,plans){const q=db.prepare(`INSERT INTO plans(household_id,date,slot,recipe_id,dry_side,liquid,confirmed,started_at,served_at,served_by,corrected) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(household_id,date,slot) DO UPDATE SET recipe_id=excluded.recipe_id,dry_side=excluded.dry_side,liquid=excluded.liquid,confirmed=excluded.confirmed`);db.exec('BEGIN');try{for(const p of plans)q.run(hid,p.date,p.slot,p.recipeId,p.drySide||null,p.liquid||null,p.confirmed?1:0,p.startedAt||null,p.servedAt||null,p.servedBy||null,p.corrected?1:0);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
function bootstrap(s){const plans=plansFor(s.household_id),date=today(),stock=db.prepare('SELECT item,available FROM stock WHERE household_id=?').all(s.household_id),events=db.prepare('SELECT id,date,kind,payload,created_at createdAt FROM events WHERE household_id=? ORDER BY created_at DESC LIMIT 30').all(s.household_id).map(e=>({...e,payload:JSON.parse(e.payload)})),serviceRecords=db.prepare('SELECT date,service_id serviceId,kind,served_at servedAt,served_by servedBy,corrected FROM service_records WHERE household_id=? AND date>=? ORDER BY date,service_id').all(s.household_id,addDays(date,-14)),byId=new Map(serviceRecords.map(x=>[x.serviceId,x])),dates=[...new Set(plans.filter(p=>p.date>=date).map(p=>p.date))],serviceSchedule=dates.flatMap(d=>services(plans.filter(p=>p.date===d),d,s.settings)).map(x=>({...x,...byId.get(x.id)}));return{role:s.role,household:{name:s.name,code:s.role==='master'?s.code:undefined,settings:s.settings},catalog,drySides,plans,services:serviceSchedule.filter(x=>x.date===date),serviceSchedule,serviceRecords,groceries:groceryTotals(plans.filter(p=>p.date>=date&&p.date<=addDays(date,6)),s.settings),stock,events,serverTime:iso()}}
function tokenFor(hid,role){const token=crypto.randomBytes(32).toString('base64url');db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(sha(token),hid,role,new Date(Date.now()+180*864e5).toISOString());return token}
function ensureWeek(hid,settings){const monday=addDays(today(),-((new Date(today()+'T12:00:00Z').getUTCDay()+6)%7));for(const offset of [0,7,14,21,28]){const start=addDays(monday,offset),existing=plansFor(hid,start,addDays(start,6)),history=plansFor(hid,addDays(start,-14),addDays(start,-1));if(existing.length<28){const made=generate(start,settings,existing,history).map(x=>({...x,confirmed:true}));savePlans(hid,made)}}}
function event(hid,kind,payload,date=today()){db.prepare('INSERT INTO events VALUES(?,?,?,?,?,?)').run(id(),hid,date,kind,JSON.stringify(payload),iso())}
function validPin(x){return /^\d{4,8}$/.test(String(x||''))}
function code(){for(let i=0;i<20;i++){const c=crypto.randomInt(100000,1000000).toString();if(!db.prepare('SELECT 1 FROM households WHERE code=?').get(c))return c}throw Error('Could not create household code')}

async function api(req,res,url){
 if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,time:iso()});
 if(req.method==='GET'&&url.pathname==='/api/download')return json(res,200,{apkUrl:process.env.APK_URL||'',version:'1.0.0'});
 if(req.method==='GET'&&url.pathname==='/api/qr'){const text=url.searchParams.get('text')||'';if(!/^https:\/\//.test(text)||text.length>500)return json(res,400,{error:'Invalid download URL.'});const svg=await QRCode.toString(text,{type:'svg',margin:1,color:{dark:'#173d32',light:'#ffffff'}});res.writeHead(200,{'content-type':'image/svg+xml','cache-control':'public, max-age=3600'});return res.end(svg)}
 if(req.method==='POST'&&url.pathname==='/api/setup/master'){const x=await body(req);if(!validPin(x.masterPin)||!validPin(x.cookPin))return json(res,400,{error:'Use a 4–8 digit PIN.'});const hid=id(),invite=code(),settings=defaultSettings();db.prepare('INSERT INTO households VALUES(?,?,?,?,?,?,?)').run(hid,invite,String(x.householdName||'Our Family').slice(0,80),sha(x.masterPin),sha(x.cookPin),JSON.stringify(settings),iso());ensureWeek(hid,settings);return json(res,201,{token:tokenFor(hid,'master'),role:'master',householdCode:invite});}
 if(req.method==='POST'&&url.pathname==='/api/setup/join'){const x=await body(req),h=db.prepare('SELECT * FROM households WHERE code=?').get(String(x.householdCode||'').trim());if(!h||sha(x.cookPin)!==h.cook_hash)return json(res,401,{error:'Use the six-digit code shown on the Master phone and the Cook PIN created by the Master.'});return json(res,200,{token:tokenFor(h.id,'cook'),role:'cook'});}
 if(req.method==='POST'&&url.pathname==='/api/login'){const x=await body(req),h=db.prepare('SELECT * FROM households WHERE code=?').get(String(x.householdCode||'')),role=x.role==='cook'?'cook':'master';if(!h||sha(x.pin)!==h[role+'_hash'])return json(res,401,{error:'Household code or PIN is incorrect.'});return json(res,200,{token:tokenFor(h.id,role),role});}
 const s=session(req);if(!s)return json(res,401,{error:'Sign in required.'});ensureWeek(s.household_id,s.settings);
 if(req.method==='GET'&&url.pathname==='/api/bootstrap')return json(res,200,bootstrap(s));
 if(req.method==='POST'&&url.pathname==='/api/settings'&&s.role==='master'){const x=await body(req),next={...s.settings,...x,people:s.settings.people,elders:s.settings.elders};db.prepare('UPDATE households SET settings=? WHERE id=?').run(JSON.stringify(next),s.household_id);event(s.household_id,'settings_updated',{});return json(res,200,{ok:true});}
 if(req.method==='POST'&&url.pathname==='/api/plan'&&s.role==='master'){const x=await body(req);if(!dateOK(x.date)||!['breakfast','lunch','snack','dinner'].includes(x.slot)||!catalog.some(r=>r.id===x.recipeId&&r.slot===x.slot))return json(res,400,{error:'Invalid meal selection.'});const old=db.prepare('SELECT started_at,served_at FROM plans WHERE household_id=? AND date=? AND slot=?').get(s.household_id,x.date,x.slot);if(old?.started_at||old?.served_at)return json(res,409,{error:'This meal is already started or served.'});const repeat=db.prepare('SELECT date FROM plans WHERE household_id=? AND recipe_id=? AND date>=? AND date<=? AND date<>? LIMIT 1').get(s.household_id,x.recipeId,addDays(x.date,-13),addDays(x.date,13),x.date);if(repeat)return json(res,409,{error:`That exact dish is already planned on ${repeat.date}. Choose a real variant to keep the 14-day gap.`});db.prepare(`INSERT INTO plans(household_id,date,slot,recipe_id,dry_side,liquid,confirmed) VALUES(?,?,?,?,?,?,1) ON CONFLICT(household_id,date,slot) DO UPDATE SET recipe_id=excluded.recipe_id,dry_side=excluded.dry_side,liquid=excluded.liquid,confirmed=1`).run(s.household_id,x.date,x.slot,x.recipeId,x.slot==='lunch'?(x.drySide||drySides[0].id):null,x.slot==='lunch'?['Rasam','Kattu','Sambar'][new Date(x.date+'T12:00:00Z').getUTCDay()%3]:null);event(s.household_id,'meal_changed',{date:x.date,slot:x.slot,recipeId:x.recipeId});return json(res,200,bootstrap(s));}
 if(req.method==='POST'&&url.pathname==='/api/regenerate'&&s.role==='master'){const x=await body(req),start=dateOK(x.start)?x.start:today(),existing=plansFor(s.household_id,start,addDays(start,6)),history=plansFor(s.household_id,addDays(start,-14),addDays(start,-1)),made=generate(start,s.settings,existing,history).map(p=>({...p,confirmed:true}));savePlans(s.household_id,made);event(s.household_id,'week_regenerated',{start});return json(res,200,bootstrap(s));}
 if(req.method==='POST'&&url.pathname==='/api/service'){const x=await body(req),match=/^(\d{4}-\d{2}-\d{2})_(\d+)$/.exec(String(x.serviceId||'')),date=match?.[1],idx=Number(match?.[2]),def=schedule[idx];if(!dateOK(date)||!def)return json(res,400,{error:'Invalid service.'});const kind=def[1],when=x.servedAt&&Number.isFinite(Date.parse(x.servedAt))?new Date(x.servedAt).toISOString():iso();db.prepare(`INSERT INTO service_records VALUES(?,?,?,?,?,?,?) ON CONFLICT(household_id,date,service_id) DO UPDATE SET served_at=excluded.served_at,served_by=excluded.served_by,corrected=excluded.corrected`).run(s.household_id,date,x.serviceId,kind,when,s.role,x.corrected?1:0);if(['breakfast','lunch','snack','dinner'].includes(kind))db.prepare('UPDATE plans SET served_at=?,served_by=?,corrected=? WHERE household_id=? AND date=? AND slot=?').run(when,s.role,x.corrected?1:0,s.household_id,date,kind);event(s.household_id,'served',{date,serviceId:x.serviceId,kind,at:when,corrected:!!x.corrected});return json(res,200,bootstrap(s));}
 if(req.method==='DELETE'&&url.pathname==='/api/service'){const x=await body(req),match=/^(\d{4}-\d{2}-\d{2})_(\d+)$/.exec(String(x.serviceId||'')),date=match?.[1],idx=Number(match?.[2]),def=schedule[idx];if(!dateOK(date)||!def)return json(res,400,{error:'Invalid service.'});const kind=def[1];db.prepare('DELETE FROM service_records WHERE household_id=? AND date=? AND service_id=?').run(s.household_id,date,x.serviceId);if(['breakfast','lunch','snack','dinner'].includes(kind))db.prepare('UPDATE plans SET served_at=NULL,served_by=NULL,corrected=0 WHERE household_id=? AND date=? AND slot=?').run(s.household_id,date,kind);event(s.household_id,'service_undone',{date,serviceId:x.serviceId,kind});return json(res,200,bootstrap(s));}
 if(req.method==='POST'&&url.pathname==='/api/start'){const x=await body(req);db.prepare('UPDATE plans SET started_at=? WHERE household_id=? AND date=? AND slot=? AND served_at IS NULL').run(iso(),s.household_id,x.date,x.slot);event(s.household_id,'started',{date:x.date,slot:x.slot});return json(res,200,bootstrap(s));}
 if(req.method==='POST'&&url.pathname==='/api/issue'){const x=await body(req);if(!['missing','late','clarify'].includes(x.type))return json(res,400,{error:'Invalid issue.'});event(s.household_id,'issue',{type:x.type,note:String(x.note||'').slice(0,300)});return json(res,200,{ok:true});}
 if(req.method==='POST'&&url.pathname==='/api/stock'){const x=await body(req);db.prepare(`INSERT INTO stock VALUES(?,?,?,?) ON CONFLICT(household_id,item) DO UPDATE SET available=excluded.available,updated_at=excluded.updated_at`).run(s.household_id,String(x.item||'').slice(0,100),x.available?1:0,iso());return json(res,200,{ok:true});}
 return json(res,404,{error:'Not found.'});
}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.json':'application/json','.webmanifest':'application/manifest+json'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/'))return await api(req,res,url);let file=path.join(publicDir,url.pathname==='/'?'index.html':url.pathname);if(!file.startsWith(publicDir))return json(res,403,{error:'Forbidden'});try{if((await stat(file)).isDirectory())file=path.join(file,'index.html')}catch{file=path.join(publicDir,'index.html')}const buf=await readFile(file);res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream','cache-control':file.endsWith('index.html')?'no-cache':'public, max-age=3600'});res.end(buf)}catch(e){console.error(e);json(res,500,{error:'Server error.'})}});
server.listen(Number(process.env.PORT||4180),'0.0.0.0',()=>console.log(`Family Table on http://0.0.0.0:${process.env.PORT||4180}`));
