import {catalog,drySides,generate,groceryTotals,services,schedule,today,dateOK,addDays,people} from '../src/planner.js';

const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,DELETE,OPTIONS'}});
const iso=()=>new Date().toISOString(), id=()=>crypto.randomUUID();
async function sha(x){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(x)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const defaultSettings=()=>({language:'te',timezone:'Asia/Kolkata',people,elders:['Rajamannar','Padma'],portions:Object.fromEntries(people.map(p=>[p,1])),excludes:[],rules:{liquidForElders:true,drySideAtLunch:true,fruitTwice:true,noRepeatDays:14},graceMinutes:10});
async function input(req){try{return await req.json()}catch{return{}}}
async function auth(req,env){const token=(req.headers.get('authorization')||'').replace(/^Bearer /,'');if(!token)return null;const row=await env.DB.prepare(`SELECT s.household_id,s.role,h.name,h.code,h.settings FROM sessions s JOIN households h ON h.id=s.household_id WHERE token_hash=? AND expires_at>?`).bind(await sha(token),iso()).first();return row?{...row,settings:JSON.parse(row.settings)}:null}
async function rows(env,hid,from=addDays(today(),-28),to=addDays(today(),35)){const x=await env.DB.prepare(`SELECT date,slot,recipe_id recipeId,dry_side drySide,liquid,confirmed,started_at startedAt,served_at servedAt,served_by servedBy,corrected FROM plans WHERE household_id=? AND date>=? AND date<=? ORDER BY date,CASE slot WHEN 'breakfast' THEN 1 WHEN 'lunch' THEN 2 WHEN 'snack' THEN 3 ELSE 4 END`).bind(hid,from,to).all();return x.results.map(r=>({...r,confirmed:!!r.confirmed,corrected:!!r.corrected}))}
async function save(env,hid,plans){const q=`INSERT INTO plans(household_id,date,slot,recipe_id,dry_side,liquid,confirmed,started_at,served_at,served_by,corrected) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(household_id,date,slot) DO UPDATE SET recipe_id=excluded.recipe_id,dry_side=excluded.dry_side,liquid=excluded.liquid,confirmed=excluded.confirmed`;await env.DB.batch(plans.map(p=>env.DB.prepare(q).bind(hid,p.date,p.slot,p.recipeId,p.drySide||null,p.liquid||null,p.confirmed?1:0,p.startedAt||null,p.servedAt||null,p.servedBy||null,p.corrected?1:0)))}
async function ensure(env,hid,settings){const d=today(),monday=addDays(d,-((new Date(d+'T12:00:00Z').getUTCDay()+6)%7));for(const offset of [0,7,14,21,28]){const start=addDays(monday,offset),existing=await rows(env,hid,start,addDays(start,6));if(existing.length<28){const history=await rows(env,hid,addDays(start,-14),addDays(start,-1)),made=generate(start,settings,existing,history).map(x=>({...x,confirmed:true}));await save(env,hid,made)}}}
async function event(env,hid,kind,payload,date=today()){await env.DB.prepare('INSERT INTO events VALUES(?,?,?,?,?,?)').bind(id(),hid,date,kind,JSON.stringify(payload),iso()).run()}
async function boot(env,s){const plans=await rows(env,s.household_id),date=today(),stock=(await env.DB.prepare('SELECT item,available FROM stock WHERE household_id=?').bind(s.household_id).all()).results,es=(await env.DB.prepare('SELECT id,date,kind,payload,created_at createdAt FROM events WHERE household_id=? ORDER BY created_at DESC LIMIT 30').bind(s.household_id).all()).results.map(e=>({...e,payload:JSON.parse(e.payload)})),serviceRecords=(await env.DB.prepare('SELECT date,service_id serviceId,kind,served_at servedAt,served_by servedBy,corrected FROM service_records WHERE household_id=? AND date>=? ORDER BY date,service_id').bind(s.household_id,addDays(date,-14)).all()).results,byId=new Map(serviceRecords.map(x=>[x.serviceId,x])),dates=[...new Set(plans.filter(p=>p.date>=date).map(p=>p.date))],serviceSchedule=dates.flatMap(d=>services(plans.filter(p=>p.date===d),d,s.settings)).map(x=>({...x,...byId.get(x.id)}));return{role:s.role,household:{name:s.name,code:s.role==='master'?s.code:undefined,settings:s.settings},catalog,drySides,plans,services:serviceSchedule.filter(x=>x.date===date),serviceSchedule,serviceRecords,groceries:groceryTotals(plans.filter(p=>p.date>=date&&p.date<=addDays(date,6)),s.settings),stock,events:es,serverTime:iso()}}
async function token(env,hid,role){const raw=crypto.randomUUID()+crypto.randomUUID(),expires=new Date(Date.now()+180*864e5).toISOString();await env.DB.prepare('INSERT INTO sessions VALUES(?,?,?,?)').bind(await sha(raw),hid,role,expires).run();return raw}
async function invite(env){for(let n=0;n<20;n++){const c=String(Math.floor(100000+Math.random()*900000));if(!await env.DB.prepare('SELECT 1 FROM households WHERE code=?').bind(c).first())return c}throw Error('Invite unavailable')}
const validPin=x=>/^\d{4,8}$/.test(String(x||''));
async function api(req,env,url){
 if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,DELETE,OPTIONS'}});
 if(req.method==='GET'&&url.pathname==='/api/health')return json({ok:true,time:iso()});
 if(req.method==='GET'&&url.pathname==='/api/download')return json({apkUrl:env.APK_URL||'',version:'1.0.0'});
 if(req.method==='POST'&&url.pathname==='/api/setup/master'){const x=await input(req);if(!validPin(x.masterPin)||!validPin(x.cookPin))return json({error:'Use a 4–8 digit PIN.'},400);const hid=id(),code=await invite(env),settings=defaultSettings();await env.DB.prepare('INSERT INTO households VALUES(?,?,?,?,?,?,?)').bind(hid,code,String(x.householdName||'Our Family').slice(0,80),await sha(x.masterPin),await sha(x.cookPin),JSON.stringify(settings),iso()).run();await ensure(env,hid,settings);return json({token:await token(env,hid,'master'),role:'master',householdCode:code},201)}
 if(req.method==='POST'&&url.pathname==='/api/setup/join'){const x=await input(req),h=await env.DB.prepare('SELECT * FROM households WHERE code=?').bind(String(x.householdCode||'')).first();if(!h||await sha(x.cookPin)!==h.cook_hash)return json({error:'Household code or Cook PIN is incorrect.'},401);return json({token:await token(env,h.id,'cook'),role:'cook'})}
 if(req.method==='POST'&&url.pathname==='/api/login'){const x=await input(req),h=await env.DB.prepare('SELECT * FROM households WHERE code=?').bind(String(x.householdCode||'')).first(),role=x.role==='cook'?'cook':'master';if(!h||await sha(x.pin)!==h[role+'_hash'])return json({error:'Household code or PIN is incorrect.'},401);return json({token:await token(env,h.id,role),role})}
 const s=await auth(req,env);if(!s)return json({error:'Sign in required.'},401);await ensure(env,s.household_id,s.settings);
 if(req.method==='GET'&&url.pathname==='/api/bootstrap')return json(await boot(env,s));
 if(req.method==='POST'&&url.pathname==='/api/settings'&&s.role==='master'){const x=await input(req),next={...s.settings,...x,people:s.settings.people,elders:s.settings.elders};await env.DB.prepare('UPDATE households SET settings=? WHERE id=?').bind(JSON.stringify(next),s.household_id).run();await event(env,s.household_id,'settings_updated',{});return json({ok:true})}
 if(req.method==='POST'&&url.pathname==='/api/plan'&&s.role==='master'){const x=await input(req);if(!dateOK(x.date)||!['breakfast','lunch','snack','dinner'].includes(x.slot)||!catalog.some(r=>r.id===x.recipeId&&r.slot===x.slot))return json({error:'Invalid meal selection.'},400);const old=await env.DB.prepare('SELECT started_at,served_at FROM plans WHERE household_id=? AND date=? AND slot=?').bind(s.household_id,x.date,x.slot).first();if(old?.started_at||old?.served_at)return json({error:'This meal is already started or served.'},409);const repeat=await env.DB.prepare('SELECT date FROM plans WHERE household_id=? AND recipe_id=? AND date>=? AND date<=? AND date<>? LIMIT 1').bind(s.household_id,x.recipeId,addDays(x.date,-13),addDays(x.date,13),x.date).first();if(repeat)return json({error:`That exact dish is already planned on ${repeat.date}. Choose a real variant to keep the 14-day gap.`},409);await env.DB.prepare(`INSERT INTO plans(household_id,date,slot,recipe_id,dry_side,liquid,confirmed) VALUES(?,?,?,?,?,?,1) ON CONFLICT(household_id,date,slot) DO UPDATE SET recipe_id=excluded.recipe_id,dry_side=excluded.dry_side,liquid=excluded.liquid,confirmed=1`).bind(s.household_id,x.date,x.slot,x.recipeId,x.slot==='lunch'?(x.drySide||drySides[0].id):null,x.slot==='lunch'?['Rasam','Kattu','Sambar'][new Date(x.date+'T12:00:00Z').getUTCDay()%3]:null).run();await event(env,s.household_id,'meal_changed',{date:x.date,slot:x.slot,recipeId:x.recipeId});return json(await boot(env,s))}
 if(req.method==='POST'&&url.pathname==='/api/regenerate'&&s.role==='master'){const x=await input(req),start=dateOK(x.start)?x.start:today(),existing=await rows(env,s.household_id,start,addDays(start,6)),history=await rows(env,s.household_id,addDays(start,-14),addDays(start,-1)),made=generate(start,s.settings,existing,history).map(p=>({...p,confirmed:true}));await save(env,s.household_id,made);await event(env,s.household_id,'week_regenerated',{start});return json(await boot(env,s))}
 if(req.method==='POST'&&url.pathname==='/api/service'){const x=await input(req),match=/^(\d{4}-\d{2}-\d{2})_(\d+)$/.exec(String(x.serviceId||'')),date=match?.[1],idx=Number(match?.[2]),def=schedule[idx];if(!dateOK(date)||!def)return json({error:'Invalid service.'},400);const kind=def[1],when=x.servedAt&&Number.isFinite(Date.parse(x.servedAt))?new Date(x.servedAt).toISOString():iso();await env.DB.prepare(`INSERT INTO service_records VALUES(?,?,?,?,?,?,?) ON CONFLICT(household_id,date,service_id) DO UPDATE SET served_at=excluded.served_at,served_by=excluded.served_by,corrected=excluded.corrected`).bind(s.household_id,date,x.serviceId,kind,when,s.role,x.corrected?1:0).run();if(['breakfast','lunch','snack','dinner'].includes(kind))await env.DB.prepare('UPDATE plans SET served_at=?,served_by=?,corrected=? WHERE household_id=? AND date=? AND slot=?').bind(when,s.role,x.corrected?1:0,s.household_id,date,kind).run();await event(env,s.household_id,'served',{date,serviceId:x.serviceId,kind,at:when,corrected:!!x.corrected});return json(await boot(env,s))}
 if(req.method==='DELETE'&&url.pathname==='/api/service'){const x=await input(req),match=/^(\d{4}-\d{2}-\d{2})_(\d+)$/.exec(String(x.serviceId||'')),date=match?.[1],idx=Number(match?.[2]),def=schedule[idx];if(!dateOK(date)||!def)return json({error:'Invalid service.'},400);const kind=def[1];await env.DB.prepare('DELETE FROM service_records WHERE household_id=? AND date=? AND service_id=?').bind(s.household_id,date,x.serviceId).run();if(['breakfast','lunch','snack','dinner'].includes(kind))await env.DB.prepare('UPDATE plans SET served_at=NULL,served_by=NULL,corrected=0 WHERE household_id=? AND date=? AND slot=?').bind(s.household_id,date,kind).run();await event(env,s.household_id,'service_undone',{date,serviceId:x.serviceId,kind});return json(await boot(env,s))}
 if(req.method==='POST'&&url.pathname==='/api/start'){const x=await input(req);await env.DB.prepare('UPDATE plans SET started_at=? WHERE household_id=? AND date=? AND slot=? AND served_at IS NULL').bind(iso(),s.household_id,x.date,x.slot).run();await event(env,s.household_id,'started',{date:x.date,slot:x.slot});return json(await boot(env,s))}
 if(req.method==='POST'&&url.pathname==='/api/issue'){const x=await input(req);if(!['missing','late','clarify'].includes(x.type))return json({error:'Invalid issue.'},400);await event(env,s.household_id,'issue',{type:x.type,note:String(x.note||'').slice(0,300)});return json({ok:true})}
 if(req.method==='POST'&&url.pathname==='/api/stock'){const x=await input(req);await env.DB.prepare(`INSERT INTO stock VALUES(?,?,?,?) ON CONFLICT(household_id,item) DO UPDATE SET available=excluded.available,updated_at=excluded.updated_at`).bind(s.household_id,String(x.item||'').slice(0,100),x.available?1:0,iso()).run();return json({ok:true})}
 return json({error:'Not found.'},404)
}
export default {async fetch(req,env){try{const url=new URL(req.url);if(url.pathname.startsWith('/api/'))return await api(req,env,url);return env.ASSETS.fetch(req)}catch(e){console.error(e);return json({error:'Service temporarily unavailable.'},500)}}};
