export const people=['Sireesha','Vamsi','Samhit','Sanvika','Rajamannar','Padma'];
// Recipe quantities are per adult-equivalent portion. Owner reviews portions at setup.
const rows=[
['idli','breakfast','Idli Sambar','ఇడ్లీ సాంబార్','इडली सांभर',30,480,'Idli batter:180:g;Sambar:150:ml','Ferment batter ahead','పిండి ముందుగా పులియబెట్టండి','घोल पहले तैयार करें',''],
['pesarattu','breakfast','Pesarattu','పెసరట్టు','पेसरट्टू',25,360,'Whole mung:70:g;Rice:15:g','Soak mung ahead','పెసలు ముందుగా నానబెట్టండి','मूंग पहले भिगोएं',''],
['poha','breakfast','Vegetable poha','అటుకుల ఉప్మా','वेज पोहा',20,0,'Poha:70:g;Mixed vegetables:60:g','Wash and chop vegetables','కూరగాయలు కడిగి తరగండి','सब्ज़ियां धोकर काटें',''],
['uttapam','breakfast','Vegetable uttapam','వెజ్ ఊతప్పం','वेज उत्तपम',25,480,'Dosa batter:180:g;Mixed vegetables:60:g','Ferment batter ahead','పిండి ముందుగా పులియబెట్టండి','घोल पहले तैयार करें',''],
['pongal','breakfast','Ven pongal','పొంగలి','पोंगल',30,0,'Rice:60:g;Moong dal:30:g;Ghee:5:g','Wash rice and dal','బియ్యం పప్పు కడగండి','चावल और दाल धोएं','milk'],
['sandwich','breakfast','Vegetable sandwich','వెజ్ సాండ్‌విచ్','वेज सैंडविच',20,0,'Bread:80:g;Mixed vegetables:80:g','Chop vegetables','కూరగాయలు తరగండి','सब्ज़ियां काटें','wheat'],
['dhokla','breakfast','Dhokla','ఢోక్లా','ढोकला',35,0,'Gram flour:70:g;Curd:30:ml','Prepare steamer','ఆవిరి పాత్ర సిద్ధం చేయండి','स्टीमर तैयार करें','milk'],
['ragi','breakfast','Ragi dosa','రాగి దోశ','रागी डोसा',25,0,'Ragi flour:60:g;Rice flour:30:g','Mix batter','పిండి కలపండి','घोल मिलाएं',''],
['pappu','lunch','Rice & pappu','అన్నం & పప్పు','चावल और दाल',35,0,'Rice:75:g;Toor dal:40:g','Cook dal','పప్పు ఉడికించండి','दाल पकाएं',''],
['pulao','lunch','Vegetable pulao','వెజ్ పులావ్','वेज पुलाव',35,0,'Rice:80:g;Mixed vegetables:100:g','Wash rice; chop vegetables','బియ్యం కడిగి కూరగాయలు తరగండి','चावल धोएं; सब्ज़ियां काटें',''],
['sambar-rice','lunch','Sambar rice','సాంబార్ అన్నం','सांभर चावल',40,0,'Rice:70:g;Toor dal:30:g;Mixed vegetables:80:g','Cook dal and vegetables','పప్పు కూరగాయలు ఉడికించండి','दाल और सब्ज़ियां पकाएं',''],
['lemon-rice','lunch','Lemon rice','నిమ్మకాయ అన్నం','नींबू चावल',25,0,'Rice:80:g;Lemon:0.5:piece','Cook rice','అన్నం వండండి','चावल पकाएं',''],
['curd-rice','lunch','Curd rice','పెరుగు అన్నం','दही चावल',25,0,'Rice:70:g;Curd:120:ml','Cook and cool rice','అన్నం వండి చల్లార్చండి','चावल पकाकर ठंडा करें','milk'],
['chole','lunch','Chole & rice','చోలే & అన్నం','छोले चावल',45,480,'Chickpeas:70:g;Rice:70:g','Soak chickpeas ahead','శనగలు ముందుగా నానబెట్టండి','चना पहले भिगोएं',''],
['biryani','lunch','Vegetable biryani','వెజ్ బిర్యానీ','वेज बिरयानी',45,0,'Rice:80:g;Mixed vegetables:120:g;Curd:30:ml','Chop vegetables','కూరగాయలు తరగండి','सब्ज़ियां काटें','milk'],
['tomato-rice','lunch','Tomato rice','టమాటా అన్నం','टमाटर चावल',30,0,'Rice:80:g;Tomato:100:g','Chop tomatoes','టమాటాలు తరగండి','टमाटर काटें',''],
['fruit','snack','Fruit salad','పండ్ల సలాడ్','फ्रूट सलाद',15,0,'Seasonal fruit:150:g','Wash and cut fruit','పండ్లు కడిగి కోయండి','फल धोकर काटें',''],
['corn','snack','Corn chaat','మొక్కజొన్న చాట్','कॉर्न चाट',15,0,'Sweetcorn:120:g;Tomato:30:g','Cook corn','మొక్కజొన్న ఉడికించండి','मकई पकाएं',''],
['quesadilla','snack','Mini vegetable quesadilla','మినీ వెజ్ కెసడిల్లా','मिनी वेज केसडिया',25,0,'Tortilla:60:g;Cheese:25:g;Mixed vegetables:60:g','Chop vegetables','కూరగాయలు తరగండి','सब्ज़ियां काटें','milk,wheat'],
['hummus','snack','Hummus & pita','హమ్మస్ & పిటా','हम्मस और पीटा',20,480,'Chickpeas:50:g;Pita bread:50:g;Tahini:10:g','Soak and cook chickpeas ahead','శనగలు నానబెట్టి ఉడికించండి','चना भिगोकर पकाएं','sesame,wheat'],
['sushi','snack','Vegetable sushi rolls','వెజ్ సుషి రోల్స్','वेज सुशी रोल',30,0,'Rice:50:g;Cucumber:40:g;Carrot:40:g;Nori:1:piece','Cook rice; cut vegetables','అన్నం వండి కూరగాయలు కోయండి','चावल पकाएं; सब्ज़ियां काटें',''],
['pancake','snack','Mini banana pancakes','మినీ అరటి పాన్‌కేక్స్','मिनी केला पैनकेक',25,0,'Wheat flour:50:g;Banana:0.5:piece;Milk:60:ml','Mash banana; mix batter','అరటి మెదిపి పిండి కలపండి','केला मसलें; घोल मिलाएं','wheat,milk'],
['falafel','snack','Baked falafel bites','బేక్డ్ ఫలాఫెల్','बेक्ड फलाफेल',40,480,'Chickpeas:60:g;Onion:20:g','Soak chickpeas ahead','శనగలు ముందుగా నానబెట్టండి','चना पहले भिगोएं',''],
['sweet-potato','snack','Roasted sweet potato','చిలగడదుంప వేపుడు','भुनी शकरकंद',35,0,'Sweet potato:150:g','Wash and cut sweet potato','చిలగడదుంప కడిగి కోయండి','शकरकंद धोकर काटें',''],
['upma','dinner','Upma & curd','ఉప్మా & పెరుగు','उपमा और दही',25,0,'Semolina:65:g;Mixed vegetables:60:g;Curd:80:ml','Chop vegetables','కూరగాయలు తరగండి','सब्ज़ियां काटें','wheat,milk'],
['roti','dinner','Roti & vegetable curry','రోటీ & కూర','रोटी और सब्ज़ी',35,20,'Wheat flour:80:g;Mixed vegetables:150:g','Knead dough','పిండి కలపండి','आटा गूंथें','wheat'],
['soup','dinner','Vegetable soup & toast','వెజ్ సూప్ & టోస్ట్','वेज सूप और टोस्ट',30,0,'Mixed vegetables:180:g;Bread:60:g','Chop vegetables','కూరగాయలు తరగండి','सब्ज़ियां काटें','wheat'],
['khichdi','dinner','Vegetable khichdi','వెజ్ కిచిడీ','वेज खिचड़ी',30,0,'Rice:50:g;Moong dal:35:g;Mixed vegetables:80:g','Wash rice and dal','బియ్యం పప్పు కడగండి','चावल और दाल धोएं',''],
['idiyappam','dinner','Idiyappam & vegetable stew','ఇడియప్పం & వెజ్ స్టూ','इडियप्पम और वेज स्टू',40,0,'Rice flour:70:g;Mixed vegetables:120:g;Coconut milk:60:ml','Prepare dough and vegetables','పిండి కూరగాయలు సిద్ధం చేయండి','आटा और सब्ज़ियां तैयार करें',''],
['dosa','dinner','Dosa & coconut chutney','దోశ & కొబ్బరి పచ్చడి','डोसा और नारियल चटनी',30,480,'Dosa batter:180:g;Coconut:35:g','Ferment batter ahead','పిండి ముందుగా పులియబెట్టండి','घोल पहले तैयार करें',''],
['appam','dinner','Appam & vegetable stew','అప్పం & వెజ్ స్టూ','अप्पम और वेज स्टू',35,480,'Appam batter:180:g;Mixed vegetables:100:g;Coconut milk:60:ml','Ferment batter ahead','పిండి ముందుగా పులియబెట్టండి','घोल पहले तैयार करें',''],
['millet','dinner','Millet vegetable pongal','చిరుధాన్య పొంగలి','मिलेट पोंगल',35,0,'Millet:60:g;Moong dal:30:g;Mixed vegetables:70:g','Wash millet and dal','చిరుధాన్యం పప్పు కడగండి','मिलेट और दाल धोएं','']
];
export const catalog=rows.map(([id,slot,en,te,hi,cook,lead,items,prepEn,prepTe,prepHi,allergens])=>({id,slot,name:{en,te,hi},cook,lead,prep:{en:prepEn,te:prepTe,hi:prepHi},allergens:allergens?allergens.split(','):[],ingredients:items.split(';').map(i=>{const[name,qty,unit]=i.split(':');return{name,qty:+qty,unit}}),videos:[{title:'Hebbars Kitchen',url:'https://www.youtube.com/results?search_query='+encodeURIComponent(en+' recipe Hebbars Kitchen')},{title:'HomeCookingShow',url:'https://www.youtube.com/results?search_query='+encodeURIComponent(en+' recipe HomeCookingShow')}]}));
export const drySides=[['okra','Okra stir-fry','బెండకాయ వేపుడు','भिंडी की सूखी सब्ज़ी'],['beans','Beans stir-fry','బీన్స్ పొడి కూర','बीन्स की सूखी सब्ज़ी'],['carrot','Carrot stir-fry','క్యారెట్ పొడి కూర','गाजर की सूखी सब्ज़ी'],['cabbage','Cabbage stir-fry','క్యాబేజీ పొడి కూర','पत्तागोभी की सूखी सब्ज़ी'],['ivy-gourd','Ivy gourd stir-fry','దొండకాయ వేపుడు','कुंदरू की सूखी सब्ज़ी'],['beetroot','Beetroot stir-fry','బీట్‌రూట్ పొడి కూర','चुकंदर की सूखी सब्ज़ी'],['cauliflower','Cauliflower stir-fry','కాలీఫ్లవర్ పొడి కూర','फूलगोभी की सूखी सब्ज़ी']].map(([id,en,te,hi])=>({id,name:{en,te,hi}}));
export const slots=['breakfast','lunch','snack','dinner'];
export const schedule=[['06:00','milk',['Sireesha','Samhit','Sanvika']],['07:00','breakfast',people],['09:00','milk',['Rajamannar','Padma']],['10:30','tea',['Sireesha','Vamsi']],['11:30','tea',['Rajamannar','Padma']],['12:00','lunch',people],['12:30','buttermilk',['Sireesha','Padma','Vamsi']],['16:00','snack',people],['16:30','milk',['Sireesha','Samhit','Sanvika']],['16:30','tea',['Vamsi','Rajamannar','Padma']],['19:00','dinner',people],['19:30','buttermilk',['Sireesha','Padma','Vamsi']]];
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const addDays=(day,n)=>new Date(Date.parse(day+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
export function dateOK(d){return /^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d+'T12:00:00Z'))&&addDays(d,0)===d}
export function safeRecipes(settings,slot){const excludes=(settings.excludes||[]).map(x=>x.toLowerCase());return catalog.filter(r=>r.slot===slot&&!r.allergens.some(a=>excludes.includes(a))&&!excludes.some(x=>r.name.en.toLowerCase().includes(x)||r.ingredients.some(i=>i.name.toLowerCase().includes(x))))}
export function generate(start,settings,existing=[],history=[]){
 const result=[],used=Object.fromEntries(slots.map(s=>[s,new Set()])),last=Object.fromEntries(slots.map(s=>[s,history.filter(h=>h.slot===s&&h.recipeId).sort((a,b)=>b.date.localeCompare(a.date))[0]?.recipeId]));
 for(let day=0;day<7;day++)for(const slot of slots){const date=addDays(start,day),saved=existing.find(x=>x.date===date&&x.slot===slot);if(saved&&(saved.confirmed||saved.started||saved.served)){result.push(saved);used[slot].add(saved.recipeId);continue}const pool=safeRecipes(settings,slot),available=pool.filter(r=>!used[slot].has(r.id)),r=available.find(r=>day>0||r.id!==last[slot])||available[0];if(!r){result.push({date,slot,recipeId:null,confirmed:false,conflict:'No non-repeating dish fits the household restrictions.'});continue}used[slot].add(r.id);result.push({date,slot,recipeId:r.id,confirmed:false,drySide:slot==='lunch'?drySides[day%drySides.length].id:null,liquid:slot==='lunch'?'Rasam / Kattu':null})}
 return result;
}
export function services(plan,date,settings){return schedule.map(([time,kind,recipients],index)=>{const meal=plan.find(x=>x.date===date&&x.slot===kind),r=catalog.find(x=>x.id===meal?.recipeId),at=Date.parse(date+'T'+time+':00+05:30');return{id:date+'_'+index,date,time,kind,recipients,recipeId:r?.id||null,meal,at,prepAt:at-(r?(r.cook+r.lead):10)*60000,readyAt:at-(r?.cook||10)*60000,enabled:!slots.includes(kind)||Boolean(meal?.confirmed&&r),name:r?.name||{en:kind,te:kind==='milk'?'పాలు':kind==='tea'?'టీ':kind==='buttermilk'?'మజ్జిగ':kind,hi:kind==='milk'?'दूध':kind==='tea'?'चाय':kind==='buttermilk'?'छाछ':kind}}})}
export function groceryTotals(plans,settings){const totals=new Map(),factor=Object.values(settings.portions||{}).reduce((a,v)=>a+Number(v),0)||6;function add(name,qty,unit){const k=name+'|'+unit;totals.set(k,{name,unit,qty:Math.round(((totals.get(k)?.qty||0)+qty)*100)/100})}for(const m of plans.filter(m=>m.confirmed)){const r=catalog.find(r=>r.id===m.recipeId);r?.ingredients.forEach(i=>add(i.name,i.qty*factor,i.unit));if(m.slot==='lunch'){const side=drySides.find(d=>d.id===m.drySide);if(side)add(side.name.en.replace(' stir-fry',''),100*factor,'g');add('Rasam / Kattu',150*2,'ml')}}return [...totals.values()]}
